### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/tree-sitter-modelica#3]
We should add a GitHub workflow to test this repository. Of course this also needs some working tests from #1.

```yml
name: build-parser
run-name: Build tree-sitter-modelica

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci           # clean install
      - run: npm run build    # Run build script
      - run: npm test         # Run test script
```
